# Generated by Django 5.2 on 2025-06-05 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
    ]
