# Generated by Django 5.2 on 2025-07-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_savedrecipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(blank=True, choices=[('Ethiopian', 'Ethiopian'), ('Eritrea', 'Eritrea'), ('African', 'African'), ('Italian', 'Italian'), ('Mexican', 'Mexican'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Indian', 'Indian'), ('French', 'French'), ('American', 'American'), ('Korean', 'Korean'), ('Spanish', 'Spanish'), ('Middle Eastern', 'Middle Eastern'), ('Brazilian', 'Brazilian'), ('British', 'British')], max_length=30),
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveIntegerField(blank=True, help_text='Preparation time in minutes', null=True),
        ),
    ]
