# Generated by Django 5.2 on 2025-09-24 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_recipe_cuisine_recipe_difficulty_recipe_prep_time'),
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='userApp.userprofile'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
