# Generated by Django 5.2 on 2025-09-24 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_recipe_author_delete_userprofile'),
    ]

    operations = [
      
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='savedrecipe',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='savedrecipe',
            name='user',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='SavedRecipe',
        ),
    ]
