# Generated by Django 5.2 on 2025-06-16 16:24

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_recipe_slug'),
    ]

    def generate_slugs(apps, schema_editor):
        Recipe = apps.get_model('App', 'Recipe')
        for recipe in Recipe.objects.all():
            recipe.slug = recipe.title.lower().replace(' ', '-')
            recipe.save()

    operations = [
        migrations.RunPython(generate_slugs),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(unique=True, max_length=200, blank=True),
        ),
    ]
