# Generated by Django 5.2 on 2025-10-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0002_alter_recipe_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(blank=True, choices=[('Ethiopian', 'Ethiopian'), ('Eritrea', 'Eritrea'), ('African', 'African'), ('Italian', 'Italian'), ('Mexican', 'Mexican'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Indian', 'Indian'), ('French', 'French'), ('American', 'American'), ('Korean', 'Korean'), ('Spanish', 'Spanish'), ('Middle Eastern', 'Middle Eastern'), ('Brazilian', 'Brazilian'), ('British', 'British')], max_length=30),
        ),
    ]
