# Generated by Django 5.2 on 2025-06-16 16:22

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_recipe_slug'),
    ]

    def generate_slugs(apps, schema_editor):
        Recipe = apps.get_model('App', 'Recipe')
        for recipe in Recipe.objects.all():
            recipe.slug = recipe.title.lower().replace(' ', '-')
            recipe.save()

    operations = [
        migrations.RunPython(generate_slugs),
    ]
